# Build and deploy Python app to Azure Web App - agentes-economicos

name: Build and deploy Python app to Azure Web App - agentes-economicos

on:
  schedule:
    - cron: '30 23 * * *'  # Executa todos os dias às 20h30 BRT (23h30 UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application
        run: |
          zip -r release.zip . -x "venv/*" "*.git*" "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05FEEA04E1BA40CFB4CBC7032B35CED7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C33D9DD4B83F4B7AAE6F727834AEC09F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78657FA4538E4AEF87B311897C7F972B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v4
        id: deploy-to-webapp
        with:
          app-name: 'agentes-economicos'  # slot-name removido
